package netcheckers;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.Socket;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.Timer;

public class NetCheckers extends javax.swing.JFrame {

    public static void main(String[] args) {
        NetCheckers.getInstance();
        Configframe.getInstance().loadConfig();
        NetCheckers.getInstance().setVisible(true);
        NetCheckers.getInstance().checkersBoardPanel.repaint();
    }

    private static NetCheckers instance;
    public Timer timerWhite;
    public Timer timerBlack;
    public int timerWhiteTime;
    public int timerBlackTime;
    public boolean timerWhitePause = true;
    public boolean timerBlackPause = true;
    public boolean connect = false;
    public CheckersBoardPanel checkersBoardPanel;
    public ServerListiner serverListener;
    public ServerConnect serverConnect;
    public String game_type = "";
    public DefaultListModel listModel = new DefaultListModel();

    public static NetCheckers getInstance() {
        if (instance == null) {
            instance = new NetCheckers();
        }
        return instance;
    }

    private NetCheckers() {
        initComponents();
        URL url = this.getClass().getResource("icon.png");
        ImageIcon image = new ImageIcon(url);
        setIconImage(image.getImage());
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
        checkersBoardPanel = new CheckersBoardPanel();
        checkersBoardPanel.setSize(jPanelBoard.getWidth(), jPanelBoard.getHeight());
        jPanelBoard.add(checkersBoardPanel, BorderLayout.CENTER);

        setBackgroundColor(Configframe.getInstance().getColorBoardWhite());
        
        checkersBoardPanel.resizePanel();
        checkersBoardPanel.repaint();
        setBackgroundColor(Configframe.getInstance().getColorBoardWhite());
        jListMove.setModel(listModel);
        timerWhite = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (!timerWhitePause) {
                    timerWhiteTime++;
                    jLabelWhiteTime.setText(" WHITE: " + String.format("%01d:%02d",
                                                (timerWhiteTime / (60)) % 60, (timerWhiteTime) % 60));

                }
            }
        });
        timerWhite.setRepeats(true);
        timerWhite.start();

        timerBlack = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if (!timerBlackPause) {
                    timerBlackTime++;
                    jLabelBlackTime.setText(" BLACK: " + String.format("%01d:%02d",
                                                (timerWhiteTime / (60)) % 60, (timerWhiteTime) % 60));

                }
            }
        });
        timerBlack.setRepeats(true);
        timerBlack.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelContent = new javax.swing.JPanel();
        jPanelBoard = new javax.swing.JPanel();
        jPanelLog = new javax.swing.JPanel();
        jButtonSendMessage = new javax.swing.JButton();
        jTextFieldMessage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jCheckBoxRotateBoard = new javax.swing.JCheckBox();
        jButtonColorsSettings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMove = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabelWhiteTime = new javax.swing.JLabel();
        jLabelBlackTime = new javax.swing.JLabel();
        jPanelGameSettings = new javax.swing.JPanel();
        jButtonNewGame = new javax.swing.JButton();
        jComboBoxSideSelect = new javax.swing.JComboBox();
        jPanelNetSettings = new javax.swing.JPanel();
        jRadioButtonServer = new javax.swing.JRadioButton();
        jRadioButtonClient = new javax.swing.JRadioButton();
        jTextFieldIP = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelIPLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetCheckers");
        setBackground(new java.awt.Color(204, 153, 0));
        setMinimumSize(new java.awt.Dimension(545, 495));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelContent.setBackground(new java.awt.Color(204, 153, 0));

        jPanelBoard.setBackground(new java.awt.Color(102, 102, 102));
        jPanelBoard.setLayout(new java.awt.BorderLayout());

        jPanelLog.setBackground(new java.awt.Color(204, 153, 0));
        jPanelLog.setLayout(null);

        jButtonSendMessage.setText("Send");
        jButtonSendMessage.setEnabled(false);
        jButtonSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMessageActionPerformed(evt);
            }
        });
        jPanelLog.add(jButtonSendMessage);
        jButtonSendMessage.setBounds(540, 80, 70, 20);

        jTextFieldMessage.setEnabled(false);
        jPanelLog.add(jTextFieldMessage);
        jTextFieldMessage.setBounds(90, 80, 440, 20);

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(4);
        jScrollPane2.setViewportView(jTextAreaLog);

        jPanelLog.add(jScrollPane2);
        jScrollPane2.setBounds(90, 5, 520, 70);

        jLabel6.setText("Message:");
        jPanelLog.add(jLabel6);
        jLabel6.setBounds(10, 80, 80, 20);

        jLabel2.setText("Log:");
        jPanelLog.add(jLabel2);
        jLabel2.setBounds(10, 4, 80, 20);

        jPanelMenu.setBackground(new java.awt.Color(204, 153, 0));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(100, 274));
        jPanelMenu.setLayout(null);

        jCheckBoxRotateBoard.setText("rotate");
        jCheckBoxRotateBoard.setContentAreaFilled(false);
        jCheckBoxRotateBoard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRotateBoardItemStateChanged(evt);
            }
        });
        jPanelMenu.add(jCheckBoxRotateBoard);
        jCheckBoxRotateBoard.setBounds(0, 375, 80, 23);

        jButtonColorsSettings.setText("colors");
        jButtonColorsSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorsSettingsActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonColorsSettings);
        jButtonColorsSettings.setBounds(90, 375, 90, 23);

        jScrollPane1.setAutoscrolls(true);

        jListMove.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jListMove);

        jPanelMenu.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 180, 90);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You play WHITE");
        jPanelMenu.add(jLabel1);
        jLabel1.setBounds(2, 0, 170, 30);

        jLabelWhiteTime.setBackground(new java.awt.Color(204, 153, 0));
        jLabelWhiteTime.setText(" WHITE: 0:00");
        jLabelWhiteTime.setOpaque(true);
        jPanelMenu.add(jLabelWhiteTime);
        jLabelWhiteTime.setBounds(2, 30, 87, 20);
        jLabelWhiteTime.getAccessibleContext().setAccessibleDescription("");

        jLabelBlackTime.setBackground(new java.awt.Color(204, 153, 0));
        jLabelBlackTime.setText(" BLACK: 0:00");
        jLabelBlackTime.setOpaque(true);
        jPanelMenu.add(jLabelBlackTime);
        jLabelBlackTime.setBounds(90, 30, 90, 20);

        jPanelGameSettings.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelGameSettings.setOpaque(false);
        jPanelGameSettings.setLayout(null);

        jButtonNewGame.setText("New game");
        jButtonNewGame.setEnabled(false);
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });
        jPanelGameSettings.add(jButtonNewGame);
        jButtonNewGame.setBounds(10, 40, 160, 22);

        jComboBoxSideSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Server - WHITE", "Server - BLACK" }));
        jComboBoxSideSelect.setEnabled(false);
        jPanelGameSettings.add(jComboBoxSideSelect);
        jComboBoxSideSelect.setBounds(10, 10, 160, 20);

        jPanelMenu.add(jPanelGameSettings);
        jPanelGameSettings.setBounds(0, 300, 180, 70);

        jPanelNetSettings.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelNetSettings.setOpaque(false);
        jPanelNetSettings.setLayout(null);

        jRadioButtonServer.setBackground(new java.awt.Color(204, 153, 0));
        buttonGroup1.add(jRadioButtonServer);
        jRadioButtonServer.setSelected(true);
        jRadioButtonServer.setText("Server");
        jRadioButtonServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonServerMouseClicked(evt);
            }
        });
        jPanelNetSettings.add(jRadioButtonServer);
        jRadioButtonServer.setBounds(10, 10, 80, 23);

        jRadioButtonClient.setBackground(new java.awt.Color(204, 153, 0));
        buttonGroup1.add(jRadioButtonClient);
        jRadioButtonClient.setText("Client");
        jRadioButtonClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonClientMouseClicked(evt);
            }
        });
        jPanelNetSettings.add(jRadioButtonClient);
        jRadioButtonClient.setBounds(90, 10, 80, 23);

        jTextFieldIP.setText("127.0.0.1");
        jTextFieldIP.setEnabled(false);
        jPanelNetSettings.add(jTextFieldIP);
        jTextFieldIP.setBounds(80, 40, 90, 20);

        jTextFieldPort.setText("4567");
        jTextFieldPort.setToolTipText("");
        jPanelNetSettings.add(jTextFieldPort);
        jTextFieldPort.setBounds(80, 70, 90, 20);

        jLabelIPLabel.setText("Server IP:");
        jLabelIPLabel.setEnabled(false);
        jPanelNetSettings.add(jLabelIPLabel);
        jLabelIPLabel.setBounds(10, 40, 70, 20);

        jLabel5.setText("Port:");
        jPanelNetSettings.add(jLabel5);
        jLabel5.setBounds(10, 70, 60, 20);

        jButtonConnect.setText("Start server");
        jButtonConnect.setToolTipText("");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });
        jPanelNetSettings.add(jButtonConnect);
        jButtonConnect.setBounds(10, 100, 160, 22);

        jPanelMenu.add(jPanelNetSettings);
        jPanelNetSettings.setBounds(0, 160, 180, 130);

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addComponent(jPanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelLog, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jPanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLog, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRotateBoardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRotateBoardItemStateChanged
        checkersBoardPanel.rotate = jCheckBoxRotateBoard.isSelected();
        checkersBoardPanel.repaint();
    }//GEN-LAST:event_jCheckBoxRotateBoardItemStateChanged

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        if (jButtonConnect.getText().equals("Start server") || jButtonConnect.getText().equals("Connect to server")) {
            connect();
        } else {
            disconnect();
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonColorsSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorsSettingsActionPerformed
        Configframe.getInstance().setVisible(true);
    }//GEN-LAST:event_jButtonColorsSettingsActionPerformed

    private void jButtonSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMessageActionPerformed
        if (!jTextFieldMessage.getText().isEmpty()) {
            serverConnect.sendMessage("mess " + jTextFieldMessage.getText());
            addToLog(" I>>> " + jTextFieldMessage.getText());
        }
    }//GEN-LAST:event_jButtonSendMessageActionPerformed

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        startNewGame();
    }//GEN-LAST:event_jButtonNewGameActionPerformed

    private void jRadioButtonServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonServerMouseClicked
        jLabelIPLabel.setEnabled(!jRadioButtonServer.isSelected());
        jTextFieldIP.setEnabled(!jRadioButtonServer.isSelected());
        if (jRadioButtonServer.isSelected()) {
            jButtonConnect.setText("Start server");
        } else {
            jButtonConnect.setText("Connect to server");
        }
    }//GEN-LAST:event_jRadioButtonServerMouseClicked

    private void jRadioButtonClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonClientMouseClicked
        jLabelIPLabel.setEnabled(jRadioButtonClient.isSelected());
        jTextFieldIP.setEnabled(jRadioButtonClient.isSelected());
        if (!jRadioButtonClient.isSelected()) {
            jButtonConnect.setText("Start server");
        } else {
            jButtonConnect.setText("Connect to server");
        }
    }//GEN-LAST:event_jRadioButtonClientMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Configframe.getInstance().saveConfig();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonColorsSettings;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonSendMessage;
    public javax.swing.JCheckBox jCheckBoxRotateBoard;
    private javax.swing.JComboBox jComboBoxSideSelect;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelBlackTime;
    private javax.swing.JLabel jLabelIPLabel;
    public javax.swing.JLabel jLabelWhiteTime;
    private javax.swing.JList jListMove;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelGameSettings;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNetSettings;
    private javax.swing.JRadioButton jRadioButtonClient;
    private javax.swing.JRadioButton jRadioButtonServer;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldIP;
    private javax.swing.JTextField jTextFieldMessage;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables

    public void connect() {
        if (isServer()) {
            serverListener = new ServerListiner();
            serverListener.start();
            addToLog(" SYSTEM>>>Wait client connection ... ");
        } else {
            String ip = getIP();
            int port = getPort();
            addToLog(" SYSTEM>>>Connect to " + ip);
            try {
                Socket socket = new Socket(ip, port);
                serverConnect = new ServerConnect(socket);
                connect = true;
                setEnableConnection(true);
                jButtonConnect.setText("Disconnect");
            } catch (UnknownHostException e) {
                addToLog(" SYSTEM>>>Unknow host");
                setConnectButtonText(jRadioButtonServer.isSelected(),false);
                setEnableConnection(false);
                e.printStackTrace();
            } catch (IOException e) {
                addToLog(" SYSTEM>>>IO Connect error");
                setConnectButtonText(jRadioButtonServer.isSelected(),false);
                setEnableConnection(false);
                e.printStackTrace();
            }
        }
    }
    
    public void startNewGame() {
        checkersBoardPanel.initBoard();
        if (jComboBoxSideSelect.getSelectedItem().toString().equals("Server - BLACK")) {
            jCheckBoxRotateBoard.setSelected(true);
            checkersBoardPanel.myColor = CheckersBoardPanel.BLACK;
            serverConnect.sendMessage("newgame WHITE");
            jLabel1.setText("You play BLACK");
            checkersBoardPanel.nowMove = CheckersBoardPanel.WHITE;
        } else {
            jCheckBoxRotateBoard.setSelected(false);
            checkersBoardPanel.myColor = CheckersBoardPanel.WHITE;
            serverConnect.sendMessage("newgame BLACK");
            jLabel1.setText("You play WHITE");
            checkersBoardPanel.nowMove = CheckersBoardPanel.WHITE;
        }
        jLabelWhiteTime.setText(" WHITE: 0:00");
        jLabelBlackTime.setText(" BLACK: 0:00");
        timerWhitePause = true;
        timerBlackPause = true;
        timerBlackTime = 0;
        timerWhiteTime = 0;
        setWhiteMove(checkersBoardPanel.nowMove == CheckersBoardPanel.WHITE);
        listModel.clear();
        addToLog(" SYSTEM>>>New game started, " + jLabel1.getText());
        checkersBoardPanel.newline = true;
        checkersBoardPanel.gameStart = true;
        checkersBoardPanel.gameEnd = false;
        checkersBoardPanel.repaint();
    }   

    public void disconnect() {
        setEnableConnection(false);
        setEnableServer(false);
        timerWhitePause = true;
        timerBlackPause = true;
        jLabelBlackTime.setBackground(Configframe.getInstance().getColorBoardWhite());
        jLabelWhiteTime.setBackground(Configframe.getInstance().getColorBoardWhite());
        setConnectButtonText(jRadioButtonServer.isSelected(), false);
        connect = false;
        try {
            checkersBoardPanel.gameStart = false;
            if (serverConnect!=null || connect) serverConnect.closeServerConnection();
            if (serverListener!=null) serverListener.closeServerListener();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }    
    
    public void addToLog(String s) {
        jTextAreaLog.setText(jTextAreaLog.getText() + s + '\n');
        jTextFieldMessage.setText("");
        jScrollPane2.getVerticalScrollBar().setValue(jScrollPane2.getVerticalScrollBar().getMaximum());
    }

    public void setEnableConnection(boolean b) {
        jButtonSendMessage.setEnabled(b);
        jTextFieldMessage.setEnabled(b);
    }

    public void setEnableServer(boolean b) {
        jComboBoxSideSelect.setEnabled(b);
        jButtonNewGame.setEnabled(b);
        jButtonSendMessage.setEnabled(b);
        jTextFieldMessage.setEnabled(b);
    }

    public void setBackgroundColor(Color c) {
        jPanelContent.setBackground(c);
        jPanelMenu.setBackground(c);
        jPanelLog.setBackground(c);
        jRadioButtonServer.setBackground(c);
        jRadioButtonClient.setBackground(c);
        jLabelWhiteTime.setBackground(c);
        jLabelBlackTime.setBackground(c);
        jTextAreaLog.setBackground(c);
        jTextFieldMessage.setBackground(c);
        jListMove.setBackground(c);
    }

    public void setWhiteMove(boolean whiteMove) {
        if (whiteMove) {
            jLabelBlackTime.setBackground(Configframe.getInstance().getColorBoardWhite());
            if (checkersBoardPanel.myColor == CheckersBoardPanel.WHITE) jLabelWhiteTime.setBackground(new Color(255, 0, 0));
            timerWhitePause = false;
            timerBlackPause = true;
        } else {
            if (checkersBoardPanel.myColor == CheckersBoardPanel.BLACK) jLabelBlackTime.setBackground(new Color(255, 0, 0));
            jLabelWhiteTime.setBackground(Configframe.getInstance().getColorBoardWhite());
            timerWhitePause = true;
            timerBlackPause = false;
        }
        int isGameEnd = checkersBoardPanel.isGameEnd();
        if (isGameEnd == CheckersBoardPanel.WHITE) {
            addToLog("WHITE WIN!!!");
            checkersBoardPanel.gameEnd = true;
            checkersBoardPanel.gameEndWin = "WHITE WIN";
            checkersBoardPanel.gameStart = false;
            checkersBoardPanel.repaint();
        } else if (isGameEnd == CheckersBoardPanel.BLACK) {
            addToLog("BLACK WIN!!!");
            checkersBoardPanel.gameEnd = true;
            checkersBoardPanel.gameEndWin = "BLACK WIN";
            checkersBoardPanel.gameStart = false;
            checkersBoardPanel.repaint();
        }
    }

    public int getCellNumberByChar(char c) {
        switch (c) {
            case 'a':
                return 0;
            case 'b':
                return 1;
            case 'c':
                return 2;
            case 'd':
                return 3;
            case 'e':
                return 4;
            case 'f':
                return 5;
            case 'g':
                return 6;
            case 'h':
                return 7;
        }
        System.err.println("error: convert char to cell number");
        return -1;
    }

    public String getIP() {
        return jTextFieldIP.getText();
    }

    public int getPort() {
        return Integer.parseInt(jTextFieldPort.getText());
    }

    public boolean isServer() {
        return jRadioButtonServer.isSelected();
    }

    public void setServer(boolean server) {
        if (server) {
            jRadioButtonServer.setSelected(true);
        } else {
            jRadioButtonClient.setSelected(true);
        }
        setConnectButtonText(server,false);
        jLabelIPLabel.setEnabled(!server);
        jTextFieldIP.setEnabled(!server);
    }

    public void setConnectButtonText(boolean server, boolean disconnect) {
        if (disconnect){
            jButtonConnect.setText("Disconnect");
        }else if (server) {
            jButtonConnect.setText("Start server");
        } else {
            jButtonConnect.setText("Connect to server");
        }
    }

    public void setIP(String ip) {
        jTextFieldIP.setText(ip);
    }

    public void setPort(int port) {
        jTextFieldPort.setText(Integer.toString(port));
    }
    
    public void parse(String mess) {
        if (mess.isEmpty()) {
            System.out.println("parse null");
            return;
        }
        System.out.print("read " + mess + '\n');
        String otvet = "";
        String command = "";
        StringTokenizer st = new StringTokenizer(mess, " ");
        if (st.hasMoreElements()) {
            command = st.nextToken().trim();
        } else {
            return;
        }
        if (command.equals("mess")) {
            addToLog(" OPPONENT>>> " + mess.substring(5));
        } else if (command.equals("newgame")) {
            checkersBoardPanel.initBoard();
            timerWhitePause = true;
            timerBlackPause = true;
            timerBlackTime = 0;
            timerWhiteTime = 0;
            checkersBoardPanel.gameEnd = false;
            if (st.hasMoreTokens()) {
                if (st.nextToken().equals("WHITE")) {
                    checkersBoardPanel.myColor = CheckersBoardPanel.WHITE;
                    jCheckBoxRotateBoard.setSelected(false);
                    jLabel1.setText("You play WHITE");
                    checkersBoardPanel.nowMove = CheckersBoardPanel.WHITE;
                } else {
                    checkersBoardPanel.myColor = CheckersBoardPanel.BLACK;
                    jCheckBoxRotateBoard.setSelected(true);
                    jLabel1.setText("You play BLACK");
                    checkersBoardPanel.nowMove = CheckersBoardPanel.WHITE;
                }
            }
            addToLog(" SYSTEM>>>New game started, " + jLabel1.getText());
            jLabelWhiteTime.setText(" WHITE: 0:00");
            jLabelBlackTime.setText(" BLACK: 0:00");
            setWhiteMove(checkersBoardPanel.nowMove == CheckersBoardPanel.WHITE);
            listModel.clear();
            checkersBoardPanel.gameStart = true;
            checkersBoardPanel.newline = true;
            checkersBoardPanel.repaint();
        } else if (command.equals("move")) {
            int i_where = Integer.parseInt(st.nextToken());
            int j_where = Integer.parseInt(st.nextToken());
            int i_end = Integer.parseInt(st.nextToken());
            int j_end = Integer.parseInt(st.nextToken());
            checkersBoardPanel.board[j_end][i_end] = checkersBoardPanel.board[j_where][i_where];
            checkersBoardPanel.board[j_where][i_where] = 0;
            checkersBoardPanel.nowMove = (checkersBoardPanel.nowMove == CheckersBoardPanel.WHITE) ? CheckersBoardPanel.BLACK : CheckersBoardPanel.WHITE;
            setWhiteMove(checkersBoardPanel.nowMove == CheckersBoardPanel.WHITE);
            checkersBoardPanel.addToMoveHisotry(i_where, j_where, i_end, j_end, "");
            checkersBoardPanel.checkKings();
            checkersBoardPanel.repaint();
        } else if (command.equals("eat")) {
            int i_where = Integer.parseInt(st.nextToken());
            int j_where = Integer.parseInt(st.nextToken());
            int i_end = Integer.parseInt(st.nextToken());
            int j_end = Integer.parseInt(st.nextToken());
            checkersBoardPanel.board[j_end][i_end] = checkersBoardPanel.board[j_where][i_where];
            checkersBoardPanel.board[j_where][i_where] = 0;
            checkersBoardPanel.board[j_where + (j_end - j_where) / 2][i_where + (i_end - i_where) / 2] = 0;
            checkersBoardPanel.checkKings();
            checkersBoardPanel.repaint();
        } else if (command.equals("eatend")) {
            checkersBoardPanel.nowMove = (checkersBoardPanel.nowMove == CheckersBoardPanel.WHITE) ? CheckersBoardPanel.BLACK : CheckersBoardPanel.WHITE;
            setWhiteMove(checkersBoardPanel.nowMove == CheckersBoardPanel.WHITE);
            checkersBoardPanel.addToMoveHisotry(0, 0, 0, 0, st.nextToken());
        }
        if (!otvet.isEmpty()) {
            serverConnect.sendMessage(otvet);
            int i_where = Integer.parseInt(st.nextToken());
            int j_where = Integer.parseInt(st.nextToken());
            int i_end = Integer.parseInt(st.nextToken());
            int j_end = Integer.parseInt(st.nextToken());
            checkersBoardPanel.board[j_end][i_end] = getInstance().checkersBoardPanel.board[j_where][i_where];
            checkersBoardPanel.board[j_where][i_where] = 0;
            checkersBoardPanel.repaint();
        }
    }

}
